package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"go.infratographer.com/x/gidx"

	"go.infratographer.com/metadata-api/internal/ent/generated"
	"go.infratographer.com/metadata-api/internal/ent/generated/metadata"
)

// FindAnnotationByID is the resolver for the findAnnotationByID field.
func (r *entityResolver) FindAnnotationByID(ctx context.Context, id gidx.PrefixedID) (*generated.Annotation, error) {
	return r.client.Annotation.Get(ctx, id)
}

// FindAnnotationNamespaceByID is the resolver for the findAnnotationNamespaceByID field.
func (r *entityResolver) FindAnnotationNamespaceByID(ctx context.Context, id gidx.PrefixedID) (*generated.AnnotationNamespace, error) {
	return r.client.AnnotationNamespace.Get(ctx, id)
}

// FindMetadataByID is the resolver for the findMetadataByID field.
func (r *entityResolver) FindMetadataByID(ctx context.Context, id gidx.PrefixedID) (*generated.Metadata, error) {
	return r.client.Metadata.Get(ctx, id)
}

// FindMetadataByNodeID is the resolver for the findMetadataByNodeID field.
func (r *entityResolver) FindMetadataByNodeID(ctx context.Context, nodeID gidx.PrefixedID) (*generated.Metadata, error) {
	return r.client.Metadata.Query().Where(metadata.NodeID(nodeID)).First(ctx)
}

// FindMetadataableByID is the resolver for the findMetadataableByID field.
func (r *entityResolver) FindMetadataableByID(ctx context.Context, id gidx.PrefixedID) (*Metadataable, error) {
	panic(fmt.Errorf("not implemented: metadata-api doesn't implement any types that support metadata"))
}

// FindResourceProviderByID is the resolver for the findResourceProviderByID field.
func (r *entityResolver) FindResourceProviderByID(ctx context.Context, id gidx.PrefixedID) (*ResourceProvider, error) {
	return &ResourceProvider{ID: id}, nil
}

// FindStatusByID is the resolver for the findStatusByID field.
func (r *entityResolver) FindStatusByID(ctx context.Context, id gidx.PrefixedID) (*generated.Status, error) {
	return r.client.Status.Get(ctx, id)
}

// FindStatusNamespaceByID is the resolver for the findStatusNamespaceByID field.
func (r *entityResolver) FindStatusNamespaceByID(ctx context.Context, id gidx.PrefixedID) (*generated.StatusNamespace, error) {
	return r.client.StatusNamespace.Get(ctx, id)
}

// FindTenantByID is the resolver for the findTenantByID field.
func (r *entityResolver) FindTenantByID(ctx context.Context, id gidx.PrefixedID) (*Tenant, error) {
	return &Tenant{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
