// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphapi

import (
	"encoding/json"

	"go.infratographer.com/metadata-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// Input information to delete an annotation.
type AnnotationDeleteInput struct {
	// The node ID for this annotation.
	NodeID gidx.PrefixedID `json:"nodeID"`
	// The namespace ID for this annotation.
	NamespaceID gidx.PrefixedID `json:"namespaceID"`
}

// Return response from annotationDelete
type AnnotationDeleteResponse struct {
	// The ID of the unset annotation.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from annotationNamespaceCreate
type AnnotationNamespaceCreatePayload struct {
	// The created annotation namespace.
	AnnotationNamespace *generated.AnnotationNamespace `json:"annotationNamespace"`
}

// Return response from annotationNamespaceDelete
type AnnotationNamespaceDeletePayload struct {
	// The ID of the deleted annotation namespace.
	DeletedID gidx.PrefixedID `json:"deletedID"`
	// The count of annotations deleted
	AnnotationDeletedCount int `json:"annotationDeletedCount"`
}

// Return response from annotationNamespaceUpdate
type AnnotationNamespaceUpdatePayload struct {
	// The updated annotation namespace.
	AnnotationNamespace *generated.AnnotationNamespace `json:"annotationNamespace"`
}

// Input information to update an annotation.
type AnnotationUpdateInput struct {
	// The node ID for this annotation.
	NodeID gidx.PrefixedID `json:"nodeID"`
	// The namespace ID for this annotation.
	NamespaceID gidx.PrefixedID `json:"namespaceID"`
	// The data to save in this annotation.
	Data json.RawMessage `json:"data"`
}

// Return response from annotationUpdate
type AnnotationUpdateResponse struct {
	// The set annotation.
	Annotation *generated.Annotation `json:"annotation"`
}

type Tenant struct {
	ID                   gidx.PrefixedID                          `json:"id"`
	AnnotationNamespaces *generated.AnnotationNamespaceConnection `json:"annotationNamespaces"`
	StatusNamespaces     *generated.StatusNamespaceConnection     `json:"statusNamespaces"`
}

func (Tenant) IsEntity() {}
