package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"go.infratographer.com/metadata-api/internal/ent/generated"
	"go.infratographer.com/metadata-api/internal/ent/generated/metadata"
	"go.infratographer.com/x/gidx"
)

// Node is the resolver for the node field.
func (r *metadataResolver) Node(ctx context.Context, obj *generated.Metadata) (*Metadataable, error) {
	return &Metadataable{ID: obj.NodeID}, nil
}

// Metadata is the resolver for the Metadata field.
func (r *queryResolver) Metadata(ctx context.Context, nodeID gidx.PrefixedID) (*generated.Metadata, error) {
	// TODO: authz check here
	return r.client.Metadata.Query().Where(metadata.NodeID(nodeID)).First(ctx)
}
