apiVersion: v2
name: metadata-api
description: A Helm chart to deploy the Infratographer metadata api
type: application
version: 0.0.1
appVersion: "0.0.1"
kubeVersion: ">=1.24"

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.2.5
  - name: reloader
    condition: reloader.enabled
    version: "1.0.28"
    repository: "https://stakater.github.io/stakater-charts"
